framework:
    secret: '%env(APP_SECRET)%'
    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler  # Changed to use DB for persistence
        cookie_secure: auto
        cookie_samesite: lax
        cookie_httponly: true
        cookie_path: /